sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.3.1"
cache: pip
install: pip install gitpython tox-travis coveralls
script:
  - python setup.py version
  - tox
after_success: coveralls
notifications:
  email: false
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    skip_cleanup: true
    skip_upload_docs: true
    user: radish
    password:
      secure: "DxGrjeFu5Wtkasa87fi6vbYtcOF+5r8NbvEJqBCNT3hzkVFcg3L4lgumk2pr9tbwIXCWzgI1i2mEwj/GBFSznC4nfnJ3befIOp7M4AR6BdLRZFVuSnrJcUrtMdy1vNS3Vy/Tm7dkvdgKB8aFaJB8g4CcbJ8adamqoJsnBzEmtbENoDXMTFqcRZU24vNbyTWLq/bakN6iFdfO80Gx8DklmMM1vJhF5OWUskPk+BIi6kt622JaTmauJ+Ilqkhp4ZyOvbs/9JtU1B3MZYXlEGDc3s3Aw50IoNfZI6+UNEZ6iPxGMd4ewRbik8QfkCkHcL/ATEkfI+FfMoZWtG5ih1tFID9D/YZEWHMuQ1ER2VTdbaOQGwDNBDk2iq58ovdxvBTpfvbjlCmSGE8ex6fRKmdzDfpIn2NJ7yXwxFCUJ8sg1yCK4R7Sl7NE+SrrdKoTZAGXcVFepstjTgzIL1Fu1rO+9Clci/G3FcjBkvd3YFwA42vAqU7MBkPwrnEy5clOhNyuVxfLZJtKJAUi/CoEnXiH9zwSqMz5nYDRb1Ou9wCqSs+QbJ1ngHRgE4d6+0i0IDK3Ke8LRRfy5jYqiFt9+ttV2FlHo250ph/pYdlqtmUewtmSaNpbMUPehNHIW7N60WA02dVUFF45mWE+TwQ034WOGGWoOmAKqWlUP5sO20JqB1s="
    on:
      python: "2.7"
      branch: master
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    user: radish
    password:
      secure: "DxGrjeFu5Wtkasa87fi6vbYtcOF+5r8NbvEJqBCNT3hzkVFcg3L4lgumk2pr9tbwIXCWzgI1i2mEwj/GBFSznC4nfnJ3befIOp7M4AR6BdLRZFVuSnrJcUrtMdy1vNS3Vy/Tm7dkvdgKB8aFaJB8g4CcbJ8adamqoJsnBzEmtbENoDXMTFqcRZU24vNbyTWLq/bakN6iFdfO80Gx8DklmMM1vJhF5OWUskPk+BIi6kt622JaTmauJ+Ilqkhp4ZyOvbs/9JtU1B3MZYXlEGDc3s3Aw50IoNfZI6+UNEZ6iPxGMd4ewRbik8QfkCkHcL/ATEkfI+FfMoZWtG5ih1tFID9D/YZEWHMuQ1ER2VTdbaOQGwDNBDk2iq58ovdxvBTpfvbjlCmSGE8ex6fRKmdzDfpIn2NJ7yXwxFCUJ8sg1yCK4R7Sl7NE+SrrdKoTZAGXcVFepstjTgzIL1Fu1rO+9Clci/G3FcjBkvd3YFwA42vAqU7MBkPwrnEy5clOhNyuVxfLZJtKJAUi/CoEnXiH9zwSqMz5nYDRb1Ou9wCqSs+QbJ1ngHRgE4d6+0i0IDK3Ke8LRRfy5jYqiFt9+ttV2FlHo250ph/pYdlqtmUewtmSaNpbMUPehNHIW7N60WA02dVUFF45mWE+TwQ034WOGGWoOmAKqWlUP5sO20JqB1s="
    on:
      python: "2.7"
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "dyKwxhUMlsbf8N7i9X9EYnlfIpc1wbcwViKhH1UfXCnQ/ruXFtpSchDpqIvi4MygUBoKsKvVzJ2Ry6viFP+amPkJMTP7tD5UfPR+vBgDHpdPn1S+7gOeeExJ10KJAYCwS1+pFGMZXn/DnfReTXrjplbNyMNGv3Hnmbtrnupa3L/fFmBwm1Syti/LeiE/vuh37PcWLPsFsFN0lPpjz5hxwRswdG7+cFroLp97mVwjYlYUK6OuvYAngvXQAauXpVCilcLX7/2lYTcuQWQW6+Z+USN/ZcUA3xSVoMv02hpZkF1CyG21ztB2mVW2CswSP2fom+uV1SRjsJczQRYBG7bgkPzpRm4pvGmQE+zX/0ndcvkngeAlY93SlQ2wvA3ObF24YDKH7aPaujnbfhLv3ezItiUKHX8ltejmcJlWrj4LmJYMU1CnfsLRS3cGG2ecJVfZ/MqrsMoL3Die+CuCauPalKYjjtmYQVeyWUOPe4qhH+9HY0E/RJcZtYKJT67QQoc9MxmzXHuelnR4sdziRd5wS38j5gwOHIm4j2PA5/w479Sjae+iMebR3fta9FCqUil0X8XMgPRLVmx9ZNDkjFFpdd0y/5vYGr34bRqyEYCli15CYC98bo0j/uWKjV+sVarOuXkijPKLOdY8wgo7S9HL3pf7VfPGfnyK6yOYwBTMNiI="
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      python: "2.7"
      branch: master
      tags: true
