sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.3.1"
cache: pip
env:
  global:
    - secure: "JoWbAvjM9CkV5BA9iUhgyqKzBKcx+xcegC0KpWoBF2oNEgLdDojgvUo6sjMt9wky3oa7qPsCU7ql5NSGm7v385Uj1uVdcB58+5I/iw2gBLxR2ykg29GTqUJ43PWc2ZHkiIaZHFbz41fxOQnZZmKuuf+BkFclNQAytac6+XT1xAKXvtwTr8Ir1DR1ic1JLSRj3U4Mk4oxi5XC4Wb2fXUkJegtloz/ulKsyT6A5/c06/pEg2A3oKe+92xbbKpWeI2ozzimkrbDynUgjybzMUln64ofdtXean13DIsJ04e+TjAxySo7JZMVEjrL6fGT5EGEy6kchI0iE0Z4q1UtK7wzNL7MyJ9AMwskEOzICZxLb8PRkU65oCySijQFm0O57rFVq46QzsNfe/aPB8NFIz3afqixTn8ymCJipfTE7SDAIdr5QwjgNjXOcaDUZuff8QCBoIjnY+3Ssc4DyjRx1l817zhwLgE96eaLjkHHjX6Nzxylgw64Hivr0CujWufufUR7Hv/Dc1DMOFSax9UBo9dHEtvYLDWW6fDrTIejSMSFMfdecN8kJ8pMD+gqGoJDdxRJope2OsZNy9oBGkjVB/SMqBhcE+pVdgbwpOeA5MzIKqabFiOuDlq3a6ZoTVNg4263echv4M+s0JSqo4xA5EwVKEN0PcwPexvKKF/wS1Aa/zQ="
install: pip install gitpython tox-travis coveralls
script:
  - python setup.py version
  - tox
after_success: coveralls
notifications:
  email: false
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://testpypi.python.org/pypi
    skip_cleanup: true
    skip_upload_docs: true
    user: thomasstreet
    password:
      secure: "0E98grPYlX834vyj+fZIukuE5s/aUxRrDC0L9L09gkeKX9RdqKwFu5oGgTjxYxpC6vZse8VnZg2TugM5uhjmC0JHBQVHi/h5XhCZqcA7XQ+Co/gaD/1+7sHeyLmym0SgNfQfJIMIhVLlZ3khgUd7Ui/BrwVYnjBiVILfj3uccjTOaCBj4PgKOBkTkrX5a3zt3gekmwHjub23/8Gc9eQLCNq06SVFzY2r12df0IDjEnBBwngS4lR+GDG+lfVvcWZba5ywsG2NMeO/AiHt9E5tBBfVJBw6lGZnFE+w0GpzKjE5WiSTJJDIiuPhZHuxH3HhEBq67IQXZpd7kPg51Z56O9BTmqqGB4yIctA8x2Dxmmzdu14ZEL6g6fIKwluQQoG8IBsNmFcfp3OXtdOmAYut2QMkyi+o/MjB91PubVBdJKTtCJFnoz+GExkQ1tkeoflIKphyHaFND9giBURwiekX8NmVQuTBuFJ9AnZ6a/EBLRMITtrTFNIiwi4c2qWrQLR4G13xghDJGytptweltD9UnDyfFXzM9B102Xc6Tj00HvihkNb3xXrOE/Rsws2+r8hRVDgyv4VleF1siqzO4+c14OoGAATXyCPavzkEnhAxEbMpkxm1VA1uLxLN1qbP7H02uk8tmOOxNCzRemY8nbAcoUOf0xmkN4iJSD+XEQPi6tg="
    on:
      python: "2.7"
      branch: master
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    user: thomasstreet
    password:
      secure: "0E98grPYlX834vyj+fZIukuE5s/aUxRrDC0L9L09gkeKX9RdqKwFu5oGgTjxYxpC6vZse8VnZg2TugM5uhjmC0JHBQVHi/h5XhCZqcA7XQ+Co/gaD/1+7sHeyLmym0SgNfQfJIMIhVLlZ3khgUd7Ui/BrwVYnjBiVILfj3uccjTOaCBj4PgKOBkTkrX5a3zt3gekmwHjub23/8Gc9eQLCNq06SVFzY2r12df0IDjEnBBwngS4lR+GDG+lfVvcWZba5ywsG2NMeO/AiHt9E5tBBfVJBw6lGZnFE+w0GpzKjE5WiSTJJDIiuPhZHuxH3HhEBq67IQXZpd7kPg51Z56O9BTmqqGB4yIctA8x2Dxmmzdu14ZEL6g6fIKwluQQoG8IBsNmFcfp3OXtdOmAYut2QMkyi+o/MjB91PubVBdJKTtCJFnoz+GExkQ1tkeoflIKphyHaFND9giBURwiekX8NmVQuTBuFJ9AnZ6a/EBLRMITtrTFNIiwi4c2qWrQLR4G13xghDJGytptweltD9UnDyfFXzM9B102Xc6Tj00HvihkNb3xXrOE/Rsws2+r8hRVDgyv4VleF1siqzO4+c14OoGAATXyCPavzkEnhAxEbMpkxm1VA1uLxLN1qbP7H02uk8tmOOxNCzRemY8nbAcoUOf0xmkN4iJSD+XEQPi6tg="
    on:
      python: "2.7"
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "0oEtV0G0Bl++eYhnd8DYLkVWvlM9mX/GkodxUMfXqBeNcxRl4Vte2U9OI+IWkFBPszvgH44x2qoyQVisCyNqPYaNtcbd0cjUbktlno3PGUEXNxD22CsqPxftUoCV0UlU30HUzrOfcgL7xcMI4dYQX4XXOdIRZjjBqtBJTlU4/WUyMGTv9RDrE2ayeLAhU2aJZ0SeQIdvDgprdcUCWZbxpB0ERwtdQS1Vn/V85j+gZLJ9bVMThqz4ddNcQ7RsuuLXCTOa33DZ0eldwtd0YUN4talMk4vXO5HkTvbzo98iZJfwDtocn0f+utmEHJ0CXlNyLxei/JX6hmSqt6UBS2ag6idhHg9j26q1cTLPK5HqDXWw165QqBAMm+fsXrMdlH8nx85zr8ypJmcQBM3t7KIAk20bbJ1+Zd7LEDvXV7F9zxZCiYSZzRVL3xwT6F28fMVDZC88cMRDt33DAjWXTXIogMNuZpR9RwOlV9p5K7CmYgIoHqsXCSDyvEC2DBBJqpmT/fBnwj+2/o3SRG968mlzhgXj1UkljklSJwVAR9aXjNiF9Mfw2F/mvqF5sLhWM16oBDbL4VDsn0DwhgZWR/shIpYPEdOsW3TqoThJ1DIAv+LscMNtDEtnKIwGeIODN6+oNa93QwdiH1QWRXRFWtF5xFuOotew6tR+0bqFU8NPs2E="
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      python: "2.7"
      branch: master
      tags: true
