sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.3.1"
cache: pip
env:
  global:
    - secure: uhTXp8tSzNJvBAINKllCYt8vTtccMeoauVYMguMOkiyw6Z5FeBNeihNmvc4cba7JR7GR/hbnatE70mfiprzBty/kaGJ0uwobF0CjCKdjuDOmyKdj8g94wSIJVgqBIjDhE6+TIWxHii0sFh5uI7rYf2rVlCbHlREj5w/42v89ujDCOyH83ppcAgotGxphLa8nisQyiAlaO12ExOGz6B1hQwL9a4Mt5oZSGj9vmEgu2yQm5aMp0yZkl1kUzreAgAwPlxF/qWtH12S06PZVZqK6zMNNbysTBX62kcTiaCymDHFiozu7pkuHS2msbEriN/7zYzBWHWgcUN4m7Ess6c7o7XMw3TyOux4XQ7BO3K46VMSjk6a9fKwSmhVRto8Avut5KxK65UVAAKtheTBgfNFpjfUEaoIn1+AXgJqf/d7UhIhIZ8ON2dBjbuix/Syb+5C56bgqhfGK3yblIvLABEyOFzej2IizaKtcxPOMrPXNNkLB2kePYtCsXlm3pMlIRh3O+KyIzFo5zntoMJy/QqMsMSLPL937dlxiriwu4meYcZNLX+swS5mXhhxfvFFbaMAiFjUYEoPnVajs5DqRAm0QM3Y3fUKShyOf1PYSKQ5iW/auSsThlreTrS1Q5iIJJof2/Hc0ZbDQnYNSN4jzkziTZyxonwAipY1qJDb7+36uv3E=
install: pip install gitpython tox-travis coveralls
script:
  - python setup.py version
  - tox
after_success: coveralls
notifications:
  email: false
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://testpypi.python.org/pypi
    skip_cleanup: true
    skip_upload_docs: true
    user: thomasstreet
    password:
      secure: "edWpfcbgw16Vl04Phu9mtmTwbZZtt4PXrCKgBgz80CDR1yP1GUeZt8SN1egolf7trxPBoJyAewe8fWX1ymqRWE2t6PgX28KqSdeSMcKIdXCdO9cVM3J5LwX4JeCN85bD782BDjJFDi71JXmcyskohrWbmoTybbPgfI15Wl7gb3JNNwVc8o43FvKVYSwV4hi/BP0kkHdQmbiDla/klzXIfDq9Vt8wy/UrueGDHYUw2/PN6xc/bRTGggsfjmHGBdPQJUn/3DqRniEOuoz729711IZG7dqrdHfx9qzlc4Xv/FLUqW+hnVK57hSMNd+WLTnrVIeqB57WSRfji1MGcUY+oNPXhsCTf3rciBauc3aVHgsggUlpbqbZJnn6IpGtjKqll3or8l6BeXuzQKgOIKI/ijGAUClSvyH5ZhSR0wD2JL7cYgTs3gTMt4n3uAlSdPsWM/bjm/Nzrr19l8BneSuAFvSl69CQ2r0i36dYsda+4hdaIwFxYUdKKXSEiK5v2YBmYvrQ0MJSx3FCaRT8KBLEZGNDb5bPbqnxS8ZI2S0vlXaz8hB2RsAlx0/QDCi/AQoJTQZOAwBfRmrR1WARrVtjVbAru+YTVGGzlhSfrniQv3e/SNw1esG+Cj2cNqMlFMci54ShIAi8meOem5ZJ3H7OYD6pKF51u1QKCYMWjeGNDCc="
    on:
      python: "2.7"
      branch: master
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    user: thomasstreet
    password:
      secure: "edWpfcbgw16Vl04Phu9mtmTwbZZtt4PXrCKgBgz80CDR1yP1GUeZt8SN1egolf7trxPBoJyAewe8fWX1ymqRWE2t6PgX28KqSdeSMcKIdXCdO9cVM3J5LwX4JeCN85bD782BDjJFDi71JXmcyskohrWbmoTybbPgfI15Wl7gb3JNNwVc8o43FvKVYSwV4hi/BP0kkHdQmbiDla/klzXIfDq9Vt8wy/UrueGDHYUw2/PN6xc/bRTGggsfjmHGBdPQJUn/3DqRniEOuoz729711IZG7dqrdHfx9qzlc4Xv/FLUqW+hnVK57hSMNd+WLTnrVIeqB57WSRfji1MGcUY+oNPXhsCTf3rciBauc3aVHgsggUlpbqbZJnn6IpGtjKqll3or8l6BeXuzQKgOIKI/ijGAUClSvyH5ZhSR0wD2JL7cYgTs3gTMt4n3uAlSdPsWM/bjm/Nzrr19l8BneSuAFvSl69CQ2r0i36dYsda+4hdaIwFxYUdKKXSEiK5v2YBmYvrQ0MJSx3FCaRT8KBLEZGNDb5bPbqnxS8ZI2S0vlXaz8hB2RsAlx0/QDCi/AQoJTQZOAwBfRmrR1WARrVtjVbAru+YTVGGzlhSfrniQv3e/SNw1esG+Cj2cNqMlFMci54ShIAi8meOem5ZJ3H7OYD6pKF51u1QKCYMWjeGNDCc="
    on:
      python: "2.7"
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: vwKH4DLqzbJQmayyoUtgknFegkh3onz/X8rKsmpds2F388GRod6H5sX27lqSA/ivkzjvZvW+ScDM5xtbJNTwMs6uy7Uuv0E0iJDy4g0cuBLr/sVUabxGR+Vc7cesSK4VTqTg2u2I3Zh8dyZUvNMAkIHIUh+nKlpCkhNTdkMd9RYtL50KIwAnz+6reQJfJ6ij7joIu5OlniErxfZPBXeOhkUPVy8nYg0ESa7q2sIOXgZVzjiaM41k0DHDvWE7FPcWBwhAcKzZp3IDtzOd8ogkzac81QiKvSfbMzoGlnHYdzIEa8QR4TkiwmhM9NN4ZMv9+MZIEEGmKT6hbfeJqr59bVFlhlAbinjCPbPvsriof3MomPlVHypcXtDd7i1bZhhFSsQ86FIkjwOzNFNEItN6/zvnavfSKZzjh/ZQL/7UIu5b7KtlEGPcpgoGVYFcGB8spfMq1w4xsOKTXMvomXIVijABatD0W8CvDSoPfV/F9IpuF7BQJAp9qLzaqRJoPFDuJZ9YXgzqIsWOG2vsAbDTfeOu3oQA3nolxoUbrjc3UgJb9oKuGh1AzETZcJXC9Af5eQ2nwy+1sa9pZXSZDYVLb5FjqOOfzOl8sr3KUNeQlHXqsoc+iZtYqWIs6IeXmZ/TfrihsTMz2yVIN0uLPoD9ySbdQdHHCzV1xxykAIKGS5c=
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      python: "2.7"
      branch: master
      tags: true
